In [ ]:
import numpy as np

In [ ]:
arr=np.array([[[11,2],[8,4]],[[5,9],[3,0]]])

In [ ]:
arr.ndim

3

In [ ]:
np.sort(arr) #asc

array([[[ 2, 11],
        [ 4,  8]],

       [[ 5,  9],
        [ 0,  3]]])

In [ ]:
np.sort(arr[::-1])

array([[[ 5,  9],
        [ 0,  3]],

       [[ 2, 11],
        [ 4,  8]]])

In [ ]:
-np.sort(-arr) #desc

array([[[11,  2],
        [ 8,  4]],

       [[ 9,  5],
        [ 3,  0]]])

In [ ]:
np.where(arr==5)

(array([1]), array([0]), array([0]))

In [ ]:
np.where(arr==11)

(array([0]), array([0]), array([0]))

In [ ]:
for x in np.nditer(arr):
   print(x)

11
2
8
4
5
9
3
0


In [ ]:
arr[1,0,0]

5

In [ ]:
arr[1,0,1]=4

In [ ]:
arr[1,0,1]+arr[0,0,0]

15